# Generated by Django 4.2.2 on 2023-08-03 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('qq', models.CharField(blank=True, max_length=30, null=True)),
                ('wechat', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'expert',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='student.User')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('view_times', models.IntegerField()),
                ('zan_times', models.IntegerField()),
                ('is_top', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('pub_time', models.DateField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('category', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, to='student.User')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-pub_time'],
            },
        ),
    ]
